### ISSUE TITLE
Is there any way to keep time-tracker from pausing when the web page reloads?

### ISSUE THREAD

**Issue by CenterForGovernmentInteroperability** [LLNL/Task-Time-Tracker#1]
Tip from Geoff:

 here's a quick sketch of how the implementation might look. When a given task timer is activated, set a flag in the task in DOM local storage indicating that the task timer is active. Then, when the page is reloaded, DOM local storage will have an indication of which timer was active prior to the reload. As the page is rebuilt, the active timer can be automatically started by the page-building logic.

**Comment by cleary3** [comment]
The fix is available in v1.7.
